[tools]
darklua = { github = "seaofvoices/darklua", version = "=0.12.0" }
wally = { github = "UpliftGames/wally", version = "=0.3.2" }
selene = { github = "Kampfkarren/selene", version = "=0.21.0" }
stylua = { github = "JohnnyMorganz/StyLua", version = "=0.18.1" }
rojo = { github = "rojo-rbx/rojo", version = "=7.4.0-rc3" }
